--
-- PostgreSQL database dump
--

\ restrict c2g2LDTMrFhajhGhjh5M1cYD0fvLuBp9Cpwfx8RtpwtkXM1vWIHfTQNWJt66cTf -- Dumped from database version 16.13 (Debian 16.13-1.pgdg13+1)
-- Dumped by pg_dump version 16.13 (Debian 16.13-1.pgdg13+1)
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;
--
-- Name: clientes; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    email character varying(255),
    nombre character varying(255),
    rol character varying(255) NOT NULL
);
ALTER TABLE public.clientes OWNER TO admin;
--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.clientes
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.clientes_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
    );
--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: admin
--

COPY public.clientes (id, email, nombre, rol)
FROM stdin;
1 juan @test.com Juan USUARIO 2 juan @test.com Juan ADMIN \.--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.clientes_id_seq', 2, true);
--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.clientes
ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);
--
-- PostgreSQL database dump complete
--

\ unrestrict c2g2LDTMrFhajhGhjh5M1cYD0fvLuBp9Cpwfx8RtpwtkXM1vWIHfTQNWJt66cTf