services:

  postgres:
    image: postgres:16

    container_name: techplanner-postgres

    environment:
      POSTGRES_DB: techplanner
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: techplanner-keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  techplanner-clientes-service:
    build:
      context: ./clientes-service
      dockerfile: Dockerfile
    container_name: techplanner-clientes-service
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/techplanner
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/techplanner/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  postgres_data: