server:
  port: 8081

spring:
  application:
    name: techplanner-clientes-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/techplanner

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/techplanner}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      poolName: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      platform: postgresql

# Spring Actuator / management
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics
